import Lake
open Lake DSL

package «proof-forge-next» where
  version := v!"0.1.0"

@[default_target]
lean_lib ProofForgeV2 where
  roots := #[`ProofForgeV2, `Examples]

lean_lib ProofForgeV2Tests where
  roots := #[
    `Tests.Core.Common,
    `Tests.Core.CommonRemaining,
    `Tests.Core.CommonScalars,
    `Tests.Core.Unicode,
    `Tests.Core.Semantics,
    `Tests.Compiler.Pipeline,
    `Tests.Compiler.TypedNameIndex,
    `Tests.Language.ParserSession,
    `Tests.Language.AggregateDeclarations,
    `Tests.Language.DeclarationAcceptance,
    `Tests.Language.ArrayTypes,
    `Tests.Language.AssertStatements,
    `Tests.Language.BitwiseNot,
    `Tests.Language.BoolLiterals,
    `Tests.Language.BytesTypes,
    `Tests.Language.CheckedDiv,
    `Tests.Language.CheckedMod,
    `Tests.Language.CheckedMul,
    `Tests.Language.CheckedNeg,
    `Tests.Language.CheckedSub,
    `Tests.Language.ConstDeclarations,
    `Tests.Language.EmitStatements,
    `Tests.Language.EventErrorDeclarations,
    `Tests.Language.ExtensionRequirements,
    `Tests.Language.FieldDeclarations,
    `Tests.Language.FnDeclarations,
    `Tests.Language.ForStatements,
    `Tests.Language.IfStatements,
    `Tests.Language.IntegerWidthDeclarations,
    `Tests.Language.LetStatements,
    `Tests.Language.OptionDeclarations,
    `Tests.Language.PrincipalDeclarations,
    `Tests.Language.UnitReturnTypes,
    `Tests.Language.InvariantDeclarations,
    `Tests.Language.ProofReferences,
    `Tests.Language.ProgramExportFixtures.A,
    `Tests.Language.ProgramExportFixtures.B,
    `Tests.Language.ProgramExportFixtures.OrderAB,
    `Tests.Language.ProgramExportFixtures.OrderBA,
    `Tests.Language.ProgramExportFixtures.Shared,
    `Tests.Language.ProgramExportSnapshot,
    `Tests.Language.ProgramExports,
    `Tests.Language.ProgramExportAcceptanceEmpty,
    `Tests.Language.ProgramExportAcceptance,
    `Tests.Language.ProgramCommandAcceptance,
    `Tests.Language.ProgramBindingFixtures.MismatchSingle,
    `Tests.Language.ProgramBindingFixtures.MismatchTable,
    `Tests.Language.ProgramBindingFixtures.Positive,
    `Tests.Language.ProgramBindingFixtures.Priority004,
    `Tests.Language.ProgramBindingFixtures.Snapshot,
    `Tests.Language.ProgramBindings,
    `Tests.Language.ProgramIdentityFixtures.Conflict,
    `Tests.Language.ProgramIdentityFixtures.Duplicate,
    `Tests.Language.ProgramIdentityFixtures.Positive,
    `Tests.Language.ProgramIdentityFixtures.Priority,
    `Tests.Language.ProgramIdentityFixtures.Snapshot,
    `Tests.Language.ProgramIdentities,
    `Tests.Language.ProgramPayloadFixtures.NegConstAlias,
    `Tests.Language.ProgramPayloadFixtures.NegImplementedBy,
    `Tests.Language.ProgramPayloadFixtures.NegOpaque,
    `Tests.Language.ProgramPayloadFixtures.NegPartial,
    `Tests.Language.ProgramPayloadFixtures.NegUnregistered,
    `Tests.Language.ProgramPayloadFixtures.NegUnsafe,
    `Tests.Language.ProgramPayloadFixtures.Positive,
    `Tests.Language.ProgramPayloadFixtures.Rich,
    `Tests.Language.ProgramPayloadFixtures.Snapshot,
    `Tests.Language.ProgramPayloads,
    `Tests.Language.ProgramShortNameFixtures.Mismatch,
    `Tests.Language.ProgramShortNameFixtures.Positive,
    `Tests.Language.ProgramShortNameFixtures.Priority004,
    `Tests.Language.ProgramShortNameFixtures.Snapshot,
    `Tests.Language.ProgramShortNames,
    `Tests.Language.ProgramSyntax,
    `Tests.Language.ShiftLeft,
    `Tests.Language.ShiftRight,
    `Tests.Language.Equal,
    `Tests.Language.NotEqual,
    `Tests.Language.LessThan,
    `Tests.Language.LessEqual,
    `Tests.Language.GreaterThan,
    `Tests.Language.GreaterEqual,
    `Tests.Language.BitwiseAnd,
    `Tests.Language.BitwiseXor,
    `Tests.Language.BitwiseOr,
    `Tests.Language.LogicalAnd,
    `Tests.Language.LogicalOr,
    `Tests.Language.StringLiterals,
    `Tests.Language.LocalFnCalls,
    `Tests.Language.ConstructorExprs,
    `Tests.Language.IndexAccesses,
    `Tests.Language.RevertStatements,
    `Tests.Language.ValueLessReturns,
    `Tests.Language.PrimitiveDeclarations,
    `Tests.Language.StateVisibility,
    `Tests.Language.SourceIdentity,
    `Tests.Language.SourceSpan,
    `Tests.Language.SourceWireAcceptance,
    `Tests.Language.SourceBoundsAcceptance,
    `Tests.Language.SourceWireCodecV1,
    `Tests.Language.SourceWireDecodeV1,
    `Tests.Language.SourceNameComponentV1,
    `Tests.Language.SourceQualifiedNameV1,
    `Tests.Language.SourceAstLeafV1,
    `Tests.Language.SourceAstSupportV1,
    `Tests.Language.SourceAstPatternV1,
    `Tests.Language.SourceAstDeclV1,
    `Tests.Language.SourceAstSpineV1,
    `Tests.Language.SourceAstSpineCodecV1,
    `Tests.Language.SourceAstSpineDeclV1,
    `Tests.Language.FrontendParity,
    `Tests.Language.Grouping,
    `Tests.Language.Loader,
    `Tests.Language.LogicalNot,
    `Tests.Materialization.Targets,
    `Tests.Materialization.NearHostModel,
    `Tests.Materialization.NoirRelationModel,
    `Tests.CLI.Emit
  ]

lean_exe proof_forge_next where
  exeName := "proof-forge-next"
  root := `ProofForgeV2.CLI.Main
  -- Parser / module loading pulls Init interpreter symbols (e.g. IO.getRandomBytes).
  supportInterpreter := true

lean_exe proof_forge_next_tests where
  exeName := "proof-forge-next-tests"
  root := `Tests
  supportInterpreter := true
