/-
  Tests.Semantic.UInt64ParitySubjectV1 — focused generic generated-subject
  checks for the one-state UInt64 parity/increment-by-two family.

  This test intentionally does not import any existing parity-instance module or
  closed byte golden. It uses the generated same-file subject declarations plus
  the contract-agnostic subject bridge.
-/
import ProofForgeV2.Core.Unicode
import ProofForgeV2.Language.ProgramElaborationV1
import ProofForgeV2.Semantic.UInt64ParitySubjectV1

namespace Tests.Semantic.UInt64ParitySubjectV1

open ProofForgeV2.Core.Common
open ProofForgeV2.Core.Unicode
open ProofForgeV2.Language
open ProofForgeV2.Semantic.WireV1

set_option maxRecDepth 500000
set_option maxHeartbeats 20000000

program ParityProbe where
  state count : UInt64
  entry increment() : UInt64 do
    count := count + 2
    return count
  view get() : UInt64 do
    return count
  invariant even : count % 2 == 0
  proof even preserving using ParityProbeProof.even

private theorem ident_count :
    validateIdentifierComponent "count" = .ok () := by
  unfold validateIdentifierComponent
  rw [if_pos (by decide)]
  simp only [requireNfc_eq_ok_of_isAscii "count" (by decide), Bind.bind, Except.bind]
  rw [if_neg (by decide)]
  simp only [Pure.pure, Except.pure]
  rfl

private theorem ident_increment :
    validateIdentifierComponent "increment" = .ok () := by
  unfold validateIdentifierComponent
  rw [if_pos (by decide)]
  simp only [requireNfc_eq_ok_of_isAscii "increment" (by decide), Bind.bind,
    Except.bind]
  rw [if_neg (by decide)]
  simp only [Pure.pure, Except.pure]
  rfl

private theorem ident_get :
    validateIdentifierComponent "get" = .ok () := by
  unfold validateIdentifierComponent
  rw [if_pos (by decide)]
  simp only [requireNfc_eq_ok_of_isAscii "get" (by decide), Bind.bind, Except.bind]
  rw [if_neg (by decide)]
  simp only [Pure.pure, Except.pure]
  rfl

private theorem ident_even :
    validateIdentifierComponent "even" = .ok () := by
  unfold validateIdentifierComponent
  rw [if_pos (by decide)]
  simp only [requireNfc_eq_ok_of_isAscii "even" (by decide), Bind.bind, Except.bind]
  rw [if_neg (by decide)]
  simp only [Pure.pure, Except.pure]
  rfl

/-- Generated structured data is exactly the generic family constructor shape. -/
example :
    ParityProbe.Proof.subjectDataV1 =
      ProofForgeV2.Semantic.UInt64ParitySubjectV1.subjectDataV1
        ParityProbe.Proof.subjectDataV1.qualifiedName "count" "increment" "get" "even" := by
  rfl

/-- Generated transparent bytes are produced by the sole production body encoder. -/
example :
    ProofForgeV2.Semantic.UInt64ParitySubjectV1.bodyEncodeOkV1
      ParityProbe.Proof.subjectDataV1 ParityProbe.Proof.subjectBytesV1 := by
  rfl

/-- The generic no-pin bridge derives validation for the actual generated
    module/namespace-qualified identity without a caller-supplied decoder or
    closed golden. -/
example
    (hstructure : validateSemanticProgramStructureV1
      ParityProbe.Proof.subjectDataV1 = .ok ()) :
    validateSemanticProgramV1 ⟨ParityProbe.Proof.subjectBytesV1⟩ =
      .ok ParityProbe.Proof.subjectDataV1 := by
  have hinvert : RootFieldInvertV1 ParityProbe.Proof.subjectDataV1 := by
    change RootFieldInvertV1
      (ProofForgeV2.Semantic.UInt64ParitySubjectV1.subjectDataV1
        ParityProbe.Proof.subjectDataV1.qualifiedName
        "count" "increment" "get" "even")
    exact ProofForgeV2.Semantic.UInt64ParitySubjectV1.rootFieldInvertV1
      ParityProbe.Proof.subjectDataV1.qualifiedName
      "count" "increment" "get" "even"
      ident_count ident_increment ident_get ident_even
  exact ProofForgeV2.Semantic.UInt64ParitySubjectV1.validate_ok_of_bodyEncode_invertV1
    ParityProbe.Proof.subjectDataV1 ParityProbe.Proof.subjectBytesV1
    ⟨ParityProbe.Proof.subjectDataV1.qualifiedName,
      "count", "increment", "get", "even", rfl⟩
    rfl rfl rfl rfl rfl rfl rfl rfl hstructure rfl hinvert

private def expect (condition : Bool) (message : String) : IO Unit := do
  unless condition do throw <| IO.userError message

def run : IO Unit := do
  match validateSemanticProgramV1 ParityProbe.Proof.subjectProgramV1 with
  | .ok data =>
      expect (data == ParityProbe.Proof.subjectDataV1)
        "generated parity subject validates to generated structured data"
      expect (data.callables.size == 3) "three generated family callables"
      expect (data.invariants.size == 1) "one generated family invariant"
  | .error error =>
      throw <| IO.userError s!"generated parity subject validation failed: {repr error}"
  match encodeSemanticProgramDataBodyV1 ParityProbe.Proof.subjectDataV1 with
  | .ok bytes =>
      expect (bytes == ParityProbe.Proof.subjectBytesV1)
        "generated parity subject body encode matches generated bytes"
  | .error error =>
      throw <| IO.userError s!"generated parity subject body encode failed: {repr error}"
  IO.println "Tests.Semantic.UInt64ParitySubjectV1: ok"

end Tests.Semantic.UInt64ParitySubjectV1
