#!/usr/bin/env python3
"""Project pinned Unicode 17 NFC tables from the committed Lean source to C.

This maintenance tool does not consult the host Unicode database.  The sole
input is the already generated, hash-pinned ProofForgeV2 UnicodeData.lean file.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_SOURCE = _ROOT / "ProofForgeV2" / "Core" / "UnicodeData.lean"
_OUTPUT = _ROOT / "scripts" / "task_qualification_unicode_v2_tables.inc"
_SOURCE_SHA256 = "8586577d010c1b59e2dc83f0b36e95b4d15e0bef8a22854ba987660f21c83fe0"
_EXPECTED_CCC = 968
_EXPECTED_DECOMPOSITION = 2081
_EXPECTED_COMPOSITION = 961


def _fail(message: str) -> "NoReturn":
    print(f"PF-TQ-UNICODE-GEN:{message}", file=sys.stderr)
    raise SystemExit(1)


def _section(text: str, start: str, end: str) -> str:
    try:
        return text.split(start, 1)[1].split(end, 1)[0]
    except IndexError:
        _fail(f"committed Unicode source section missing: {start}")


def _render() -> bytes:
    source = _SOURCE.read_bytes()
    if hashlib.sha256(source).hexdigest() != _SOURCE_SHA256:
        _fail("committed UnicodeData.lean digest drift")
    text = source.decode("utf-8")
    ccc_section = _section(
        text, "def canonicalCombiningClassTable", "structure CanonicalDecomposition"
    )
    decomposition_section = _section(
        text, "def canonicalDecompositionTable", "structure CompositionPair"
    )
    composition_section = _section(
        text, "def compositionPairTable", "/-- General_Category=Cc"
    )
    ccc = [
        (int(code, 16), int(value, 10))
        for code, value in re.findall(r"\(0x([0-9A-F]+), (\d+)\)", ccc_section)
    ]
    decompositions: list[tuple[int, tuple[int, ...]]] = []
    for code, mapping in re.findall(
        r"\{ code := 0x([0-9A-F]+), mapping := #\[([^\]]*)\] \}",
        decomposition_section,
        flags=re.S,
    ):
        values = tuple(int(value, 16) for value in re.findall(r"0x([0-9A-F]+)", mapping))
        decompositions.append((int(code, 16), values))
    compositions = [
        (int(first, 16), int(second, 16), int(composite, 16))
        for first, second, composite in re.findall(
            r"\{ first := 0x([0-9A-F]+), second := 0x([0-9A-F]+), "
            r"composite := 0x([0-9A-F]+) \}",
            composition_section,
        )
    ]
    if len(ccc) != _EXPECTED_CCC or len(decompositions) != _EXPECTED_DECOMPOSITION \
            or len(compositions) != _EXPECTED_COMPOSITION:
        _fail(
            "Unicode row-count drift "
            f"ccc={len(ccc)} decomposition={len(decompositions)} "
            f"composition={len(compositions)}"
        )
    if ccc != sorted(ccc) or decompositions != sorted(decompositions) \
            or compositions != sorted(compositions):
        _fail("Unicode source tables are not strictly sorted")
    if any(not mapping or len(mapping) > 4 for _, mapping in decompositions):
        _fail("Unicode decomposition width is outside 1..4")

    values: list[int] = []
    decomposition_rows: list[tuple[int, int, int]] = []
    for code, mapping in decompositions:
        decomposition_rows.append((code, len(values), len(mapping)))
        values.extend(mapping)

    lines = [
        "/* AUTO-GENERATED by scripts/generate_task_qualification_unicode_v2.py.",
        " * Unicode 17.0.0 / UAX #15 revision 57.",
        f" * Source SHA-256: {_SOURCE_SHA256}",
        " * DO NOT EDIT BY HAND. */",
        "",
        "static const struct pf_tq_unicode_ccc_v2 pf_tq_unicode_ccc_table_v2[] = {",
    ]
    lines.extend(f"    {{0x{code:06x}U, {value}U}}," for code, value in ccc)
    lines.extend([
        "};",
        "",
        "static const uint32_t pf_tq_unicode_decomposition_values_v2[] = {",
    ])
    for offset in range(0, len(values), 8):
        rendered = ", ".join(f"0x{value:06x}U" for value in values[offset:offset + 8])
        lines.append(f"    {rendered},")
    lines.extend([
        "};",
        "",
        "static const struct pf_tq_unicode_decomposition_v2 "
        "pf_tq_unicode_decomposition_table_v2[] = {",
    ])
    lines.extend(
        f"    {{0x{code:06x}U, {offset}U, {length}U}},"
        for code, offset, length in decomposition_rows
    )
    lines.extend([
        "};",
        "",
        "static const struct pf_tq_unicode_composition_v2 "
        "pf_tq_unicode_composition_table_v2[] = {",
    ])
    lines.extend(
        f"    {{0x{first:06x}U, 0x{second:06x}U, 0x{composite:06x}U}},"
        for first, second, composite in compositions
    )
    lines.extend([
        "};",
        "",
        f"#define PF_TQ_UNICODE_CCC_COUNT_V2 {_EXPECTED_CCC}U",
        f"#define PF_TQ_UNICODE_DECOMPOSITION_COUNT_V2 {_EXPECTED_DECOMPOSITION}U",
        f"#define PF_TQ_UNICODE_COMPOSITION_COUNT_V2 {_EXPECTED_COMPOSITION}U",
        f"#define PF_TQ_UNICODE_DECOMPOSITION_VALUE_COUNT_V2 {len(values)}U",
        "",
    ])
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = _render()
    if arguments.write:
        _OUTPUT.write_bytes(rendered)
        return 0
    try:
        actual = _OUTPUT.read_bytes()
    except OSError as exc:
        _fail(f"generated C table missing: {exc}")
    if actual != rendered:
        _fail("generated C table drift; run with --write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
